version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: the_maze_db
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'
