version: '3'
services:
  app:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AdminMic2025
      MYSQL_DATABASE: micserver
      MYSQL_PASSWORD: AdminMic2025
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - '3306:3306'