name: Secure Deploy to Azure VM

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

      - name: Execute Deployment Commands
        env:
          USER: ${{ secrets.USER }}
          AZURE_IP: ${{ secrets.AZURE_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              "$USER@$AZURE_IP" << 'EOF'
                cd ~/the-maze-back
                git fetch origin master
                git reset --hard origin/master
                sudo docker compose down
                sudo docker compose up -d --build
          EOF
